import { Track } from '../types/game';

/**
 * YouTube Playlist used for Anime Openings:
 * https://youtube.com/playlist?list=PLzSjbEiFKZ_w9zWXjVSTLi5FUlcPHwQCc
 * Total curated and verified openings: 100
 */
export const ANIME_OPENINGS_PLAYLIST_ID = 'PLzSjbEiFKZ_w9zWXjVSTLi5FUlcPHwQCc';

export const VERIFIED_YOUTUBE_TRACKS: Track[] = [
  // ==========================================
  // ANIME OPENINGS (from Playlist PLzSjbEiFKZ_w9zWXjVSTLi5FUlcPHwQCc)
  // ==========================================
  {
    id: 'yt_5yb2N3pnztU',
    title: 'SPECIALZ',
    artist: 'King Gnu',
    album: 'Jujutsu Kaisen Season 2 OP2',
    previewUrl: 'https://www.youtube.com/watch?v=5yb2N3pnztU',
    artworkUrl: 'https://img.youtube.com/vi/5yb2N3pnztU/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '5yb2N3pnztU',
  },
  {
    id: 'yt_dFlDRhvM4L0',
    title: 'KICK BACK',
    artist: 'Kenshi Yonezu',
    album: 'Chainsaw Man OP',
    previewUrl: 'https://www.youtube.com/watch?v=dFlDRhvM4L0',
    artworkUrl: 'https://img.youtube.com/vi/dFlDRhvM4L0/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'dFlDRhvM4L0',
  },
  {
    id: 'yt_v8bZVdTgXoY',
    title: 'Kaikai Kitan',
    artist: 'Eve',
    album: 'Jujutsu Kaisen OP1',
    previewUrl: 'https://www.youtube.com/watch?v=v8bZVdTgXoY',
    artworkUrl: 'https://img.youtube.com/vi/v8bZVdTgXoY/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'v8bZVdTgXoY',
  },
  {
    id: 'yt_2S4qGKmzBJE',
    title: 'The Rumbling',
    artist: 'SiM',
    album: 'Attack on Titan Final Season Part 2 OP',
    previewUrl: 'https://www.youtube.com/watch?v=2S4qGKmzBJE',
    artworkUrl: 'https://img.youtube.com/vi/2S4qGKmzBJE/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '2S4qGKmzBJE',
  },
  {
    id: 'yt_JBqxVX_LXvk',
    title: 'Inferno',
    artist: 'Mrs. GREEN APPLE',
    album: 'Fire Force OP1',
    previewUrl: 'https://www.youtube.com/watch?v=JBqxVX_LXvk',
    artworkUrl: 'https://img.youtube.com/vi/JBqxVX_LXvk/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'JBqxVX_LXvk',
  },
  {
    id: 'yt_210R0ozmLwg',
    title: 'Bling-Bang-Bang-Born',
    artist: 'Creepy Nuts',
    album: 'MASHLE: MAGIC AND MUSCLES OP2',
    previewUrl: 'https://www.youtube.com/watch?v=210R0ozmLwg',
    artworkUrl: 'https://img.youtube.com/vi/210R0ozmLwg/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '210R0ozmLwg',
  },
  {
    id: 'yt_zzJ8U8OtEsE',
    title: 'Resonance',
    artist: 'T.M.Revolution',
    album: 'Soul Eater OP1',
    previewUrl: 'https://www.youtube.com/watch?v=zzJ8U8OtEsE',
    artworkUrl: 'https://img.youtube.com/vi/zzJ8U8OtEsE/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'zzJ8U8OtEsE',
  },
  {
    id: 'yt_LKP-vZvjbh8',
    title: 'Shinzou wo Sasageyo!',
    artist: 'Linked Horizon',
    album: 'Attack on Titan Season 2 OP',
    previewUrl: 'https://www.youtube.com/watch?v=LKP-vZvjbh8',
    artworkUrl: 'https://img.youtube.com/vi/LKP-vZvjbh8/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'LKP-vZvjbh8',
  },
  {
    id: 'yt_8nNujr378EA',
    title: 'VIVID VICE',
    artist: 'Who-ya Extended',
    album: 'Jujutsu Kaisen OP2',
    previewUrl: 'https://www.youtube.com/watch?v=8nNujr378EA',
    artworkUrl: 'https://img.youtube.com/vi/8nNujr378EA/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '8nNujr378EA',
  },
  {
    id: 'yt_bgo9dJB_icw',
    title: 'Wild Side',
    artist: 'ALI',
    album: 'BEASTARS OP1',
    previewUrl: 'https://www.youtube.com/watch?v=bgo9dJB_icw',
    artworkUrl: 'https://img.youtube.com/vi/bgo9dJB_icw/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'bgo9dJB_icw',
  },
  {
    id: 'yt_7aMOurgDB-o',
    title: 'Unravel',
    artist: 'TK from Ling Toshite Sigure',
    album: 'Tokyo Ghoul OP',
    previewUrl: 'https://www.youtube.com/watch?v=7aMOurgDB-o',
    artworkUrl: 'https://img.youtube.com/vi/7aMOurgDB-o/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '7aMOurgDB-o',
  },
  {
    id: 'yt_gcgKUcJKxIs',
    title: 'Where Our Blue Is (Ao no Sumika)',
    artist: 'Tatsuya Kitani',
    album: 'Jujutsu Kaisen Season 2 OP1',
    previewUrl: 'https://www.youtube.com/watch?v=gcgKUcJKxIs',
    artworkUrl: 'https://img.youtube.com/vi/gcgKUcJKxIs/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'gcgKUcJKxIs',
  },
  {
    id: 'yt_DjUtmbZt8zc',
    title: 'My Dearest',
    artist: 'supercell',
    album: 'Guilty Crown OP1',
    previewUrl: 'https://www.youtube.com/watch?v=DjUtmbZt8zc',
    artworkUrl: 'https://img.youtube.com/vi/DjUtmbZt8zc/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'DjUtmbZt8zc',
  },
  {
    id: 'yt_PgBvV9ofjmA',
    title: 'Idol',
    artist: 'YOASOBI',
    album: 'Oshi no Ko OP',
    previewUrl: 'https://www.youtube.com/watch?v=PgBvV9ofjmA',
    artworkUrl: 'https://img.youtube.com/vi/PgBvV9ofjmA/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'PgBvV9ofjmA',
  },
  {
    id: 'yt_zVgKnfN9i34',
    title: 'Silhouette',
    artist: 'KANA-BOON',
    album: 'Naruto Shippuden OP16',
    previewUrl: 'https://www.youtube.com/watch?v=zVgKnfN9i34',
    artworkUrl: 'https://img.youtube.com/vi/zVgKnfN9i34/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'zVgKnfN9i34',
  },
  {
    id: 'yt_Q7w5IMyJ3pM',
    title: 'Peace Sign',
    artist: 'Kenshi Yonezu',
    album: 'My Hero Academia Season 2 OP1',
    previewUrl: 'https://www.youtube.com/watch?v=Q7w5IMyJ3pM',
    artworkUrl: 'https://img.youtube.com/vi/Q7w5IMyJ3pM/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'Q7w5IMyJ3pM',
  },
  {
    id: 'yt_Oo52vQyAR6w',
    title: 'Hope',
    artist: 'Namie Amuro',
    album: 'One Piece OP20',
    previewUrl: 'https://www.youtube.com/watch?v=Oo52vQyAR6w',
    artworkUrl: 'https://img.youtube.com/vi/Oo52vQyAR6w/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'Oo52vQyAR6w',
  },
  {
    id: 'yt_dM7x1PNZDo0',
    title: 'We Are!',
    artist: 'Hiroshi Kitadani',
    album: 'One Piece OP1',
    previewUrl: 'https://www.youtube.com/watch?v=dM7x1PNZDo0',
    artworkUrl: 'https://img.youtube.com/vi/dM7x1PNZDo0/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'dM7x1PNZDo0',
  },
  {
    id: 'yt_0dK7JgKivQM',
    title: 'Shoukei to Shikabane no Michi',
    artist: 'Linked Horizon',
    album: 'Attack on Titan Season 3 Part 2 OP',
    previewUrl: 'https://www.youtube.com/watch?v=0dK7JgKivQM',
    artworkUrl: 'https://img.youtube.com/vi/0dK7JgKivQM/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '0dK7JgKivQM',
  },
  {
    id: 'yt_l2j1qM7gx54',
    title: 'Sora ni Utaeba',
    artist: 'amazarashi',
    album: 'My Hero Academia Season 2 OP2',
    previewUrl: 'https://www.youtube.com/watch?v=l2j1qM7gx54',
    artworkUrl: 'https://img.youtube.com/vi/l2j1qM7gx54/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'l2j1qM7gx54',
  },
  {
    id: 'yt_KOWcj7XKnfQ',
    title: 'Clattanoia',
    artist: 'OxT',
    album: 'Overlord OP1',
    previewUrl: 'https://www.youtube.com/watch?v=KOWcj7XKnfQ',
    artworkUrl: 'https://img.youtube.com/vi/KOWcj7XKnfQ/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'KOWcj7XKnfQ',
  },
  {
    id: 'yt_yu0HjPzFYnY',
    title: 'THE DAY',
    artist: 'Porno Graffitti',
    album: 'My Hero Academia OP1',
    previewUrl: 'https://www.youtube.com/watch?v=yu0HjPzFYnY',
    artworkUrl: 'https://img.youtube.com/vi/yu0HjPzFYnY/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'yu0HjPzFYnY',
  },
  {
    id: 'yt_PbWFpzi8C94',
    title: 'Jiyuu no Tsubasa',
    artist: 'Linked Horizon',
    album: 'Attack on Titan OP2',
    previewUrl: 'https://www.youtube.com/watch?v=PbWFpzi8C94',
    artworkUrl: 'https://img.youtube.com/vi/PbWFpzi8C94/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'PbWFpzi8C94',
  },
  {
    id: 'yt_XhIA35OAIw4',
    title: 'Make my story',
    artist: 'Lenny code fiction',
    album: 'My Hero Academia Season 3 OP2',
    previewUrl: 'https://www.youtube.com/watch?v=XhIA35OAIw4',
    artworkUrl: 'https://img.youtube.com/vi/XhIA35OAIw4/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'XhIA35OAIw4',
  },
  {
    id: 'yt_tF4faMbs5oQ',
    title: 'Good Morning World!',
    artist: 'BURNOUT SYNDROMES',
    album: 'Dr. STONE OP1',
    previewUrl: 'https://www.youtube.com/watch?v=tF4faMbs5oQ',
    artworkUrl: 'https://img.youtube.com/vi/tF4faMbs5oQ/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'tF4faMbs5oQ',
  },
  {
    id: 'yt_-eYK3YP524A',
    title: 'PAPERMOON',
    artist: 'Tommy heavenly6',
    album: 'Soul Eater OP2',
    previewUrl: 'https://www.youtube.com/watch?v=-eYK3YP524A',
    artworkUrl: 'https://img.youtube.com/vi/-eYK3YP524A/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '-eYK3YP524A',
  },
  {
    id: 'yt_UjjTMNDZi-A',
    title: 'Flyers',
    artist: 'BRADIO',
    album: 'Death Parade OP',
    previewUrl: 'https://www.youtube.com/watch?v=UjjTMNDZi-A',
    artworkUrl: 'https://img.youtube.com/vi/UjjTMNDZi-A/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'UjjTMNDZi-A',
  },
  {
    id: 'yt_aaZq6SXXNt4',
    title: 'Grandeur',
    artist: 'Snow Man',
    album: 'Black Clover OP13',
    previewUrl: 'https://www.youtube.com/watch?v=aaZq6SXXNt4',
    artworkUrl: 'https://img.youtube.com/vi/aaZq6SXXNt4/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'aaZq6SXXNt4',
  },
  {
    id: 'yt_Bw-5Lka7gPE',
    title: '99',
    artist: 'MOB CHOIR',
    album: 'Mob Psycho 100 OP1',
    previewUrl: 'https://www.youtube.com/watch?v=Bw-5Lka7gPE',
    artworkUrl: 'https://img.youtube.com/vi/Bw-5Lka7gPE/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'Bw-5Lka7gPE',
  },
  {
    id: 'yt_By_JYrhx-WY',
    title: 'Cry Baby',
    artist: 'Official HIGE DANdism',
    album: 'Tokyo Revengers OP1',
    previewUrl: 'https://www.youtube.com/watch?v=By_JYrhx-WY',
    artworkUrl: 'https://img.youtube.com/vi/By_JYrhx-WY/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'By_JYrhx-WY',
  },
  {
    id: 'yt_0Vwwr3VGsYg',
    title: 'Redo',
    artist: 'Konomi Suzuki',
    album: 'Re:ZERO Season 1 OP1',
    previewUrl: 'https://www.youtube.com/watch?v=0Vwwr3VGsYg',
    artworkUrl: 'https://img.youtube.com/vi/0Vwwr3VGsYg/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '0Vwwr3VGsYg',
  },
  {
    id: 'yt_8-91y7BJ8QA',
    title: 'Easy Breezy',
    artist: 'chelmico',
    album: 'Keep Your Hands Off Eizouken! OP',
    previewUrl: 'https://www.youtube.com/watch?v=8-91y7BJ8QA',
    artworkUrl: 'https://img.youtube.com/vi/8-91y7BJ8QA/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '8-91y7BJ8QA',
  },
  {
    id: 'yt_ORDXWrL5EuQ',
    title: 'History Maker',
    artist: 'Dean Fujioka',
    album: 'Yuri!!! on ICE OP',
    previewUrl: 'https://www.youtube.com/watch?v=ORDXWrL5EuQ',
    artworkUrl: 'https://img.youtube.com/vi/ORDXWrL5EuQ/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'ORDXWrL5EuQ',
  },
  {
    id: 'yt_pEVhv4eB8Q8',
    title: 'Aiue',
    artist: 'MAISONdes feat. Minami, SAKURAmoti',
    album: 'Urusei Yatsura (2022) OP1',
    previewUrl: 'https://www.youtube.com/watch?v=pEVhv4eB8Q8',
    artworkUrl: 'https://img.youtube.com/vi/pEVhv4eB8Q8/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'pEVhv4eB8Q8',
  },
  {
    id: 'yt_eS0hCgXMnT4',
    title: 'Kaze wo Sagashite',
    artist: 'Mari Yaguchi with Straw Hat',
    album: 'One Piece OP12',
    previewUrl: 'https://www.youtube.com/watch?v=eS0hCgXMnT4',
    artworkUrl: 'https://img.youtube.com/vi/eS0hCgXMnT4/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'eS0hCgXMnT4',
  },
  {
    id: 'yt_54dp8ucsGG8',
    title: 'Believe',
    artist: 'Folder5',
    album: 'One Piece OP2',
    previewUrl: 'https://www.youtube.com/watch?v=54dp8ucsGG8',
    artworkUrl: 'https://img.youtube.com/vi/54dp8ucsGG8/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '54dp8ucsGG8',
  },
  {
    id: 'yt__6KZI74zKfE',
    title: 'Haruka Mirai',
    artist: 'Kankaku Piero',
    album: 'Black Clover OP1',
    previewUrl: 'https://www.youtube.com/watch?v=_6KZI74zKfE',
    artworkUrl: 'https://img.youtube.com/vi/_6KZI74zKfE/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '_6KZI74zKfE',
  },
  {
    id: 'yt_epZaT8B31-g',
    title: '99.9',
    artist: 'MOB CHOIR feat. sajou no hana',
    album: 'Mob Psycho 100 II OP',
    previewUrl: 'https://www.youtube.com/watch?v=epZaT8B31-g',
    artworkUrl: 'https://img.youtube.com/vi/epZaT8B31-g/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'epZaT8B31-g',
  },
  {
    id: 'yt_z9JZB08qy44',
    title: 'Hana ni Natte (Be a Flower)',
    artist: 'Ryokuoushoku Shakai',
    album: 'The Apothecary Diaries OP1',
    previewUrl: 'https://www.youtube.com/watch?v=z9JZB08qy44',
    artworkUrl: 'https://img.youtube.com/vi/z9JZB08qy44/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'z9JZB08qy44',
  },
  {
    id: 'yt_cZsj0dTTmy8',
    title: 'HANDS UP!',
    artist: 'Kota Shinzato',
    album: 'One Piece OP16',
    previewUrl: 'https://www.youtube.com/watch?v=cZsj0dTTmy8',
    artworkUrl: 'https://img.youtube.com/vi/cZsj0dTTmy8/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'cZsj0dTTmy8',
  },
  {
    id: 'yt_cM1WSovcn4I',
    title: 'Centimeter',
    artist: 'the peggies',
    album: 'Rent-a-Girlfriend OP1',
    previewUrl: 'https://www.youtube.com/watch?v=cM1WSovcn4I',
    artworkUrl: 'https://img.youtube.com/vi/cM1WSovcn4I/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'cM1WSovcn4I',
  },
  {
    id: 'yt_Tt4_enX63K0',
    title: 'Song of the Dead',
    artist: 'KANA-BOON',
    album: 'Zom 100: Bucket List of the Dead OP',
    previewUrl: 'https://www.youtube.com/watch?v=Tt4_enX63K0',
    artworkUrl: 'https://img.youtube.com/vi/Tt4_enX63K0/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'Tt4_enX63K0',
  },
  {
    id: 'yt_6CBp4qylX6I',
    title: 'This game',
    artist: 'Konomi Suzuki',
    album: 'No Game No Life OP',
    previewUrl: 'https://www.youtube.com/watch?v=6CBp4qylX6I',
    artworkUrl: 'https://img.youtube.com/vi/6CBp4qylX6I/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '6CBp4qylX6I',
  },
  {
    id: 'yt_Rm8UjBAS3cs',
    title: 'Let Me Hear',
    artist: 'Fear, and Loathing in Las Vegas',
    album: 'Parasyte -the maxim- OP',
    previewUrl: 'https://www.youtube.com/watch?v=Rm8UjBAS3cs',
    artworkUrl: 'https://img.youtube.com/vi/Rm8UjBAS3cs/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'Rm8UjBAS3cs',
  },
  {
    id: 'yt_SohCAjC-Npk',
    title: 'Sangenshoku',
    artist: 'PELICAN FANCLUB',
    album: 'Dr. STONE OP2',
    previewUrl: 'https://www.youtube.com/watch?v=SohCAjC-Npk',
    artworkUrl: 'https://img.youtube.com/vi/SohCAjC-Npk/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'SohCAjC-Npk',
  },
  {
    id: 'yt_jZvFEtR8RH0',
    title: 'RISE',
    artist: 'MADKID',
    album: 'The Rising of the Shield Hero OP1',
    previewUrl: 'https://www.youtube.com/watch?v=jZvFEtR8RH0',
    artworkUrl: 'https://img.youtube.com/vi/jZvFEtR8RH0/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'jZvFEtR8RH0',
  },
  {
    id: 'yt_QHFif7LRylw',
    title: 'Kuchizuke Diamond',
    artist: 'WEAVER',
    album: 'Yamada-kun and the Seven Witches OP',
    previewUrl: 'https://www.youtube.com/watch?v=QHFif7LRylw',
    artworkUrl: 'https://img.youtube.com/vi/QHFif7LRylw/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'QHFif7LRylw',
  },
  {
    id: 'yt_CFM_zypYFHM',
    title: 'We Are! (Remaster)',
    artist: 'Hiroshi Kitadani',
    album: 'One Piece OP10',
    previewUrl: 'https://www.youtube.com/watch?v=CFM_zypYFHM',
    artworkUrl: 'https://img.youtube.com/vi/CFM_zypYFHM/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'CFM_zypYFHM',
  },
  {
    id: 'yt_eRJyYfAq2tk',
    title: 'Contradiction',
    artist: 'KSUKE feat. Tyler Carter',
    album: 'The God of High School OP',
    previewUrl: 'https://www.youtube.com/watch?v=eRJyYfAq2tk',
    artworkUrl: 'https://img.youtube.com/vi/eRJyYfAq2tk/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'eRJyYfAq2tk',
  },
  {
    id: 'yt_f8d3bW42aFY',
    title: 'COOLEST',
    artist: 'Customi-Z',
    album: 'Haven\'t You Heard? I\'m Sakamoto OP',
    previewUrl: 'https://www.youtube.com/watch?v=f8d3bW42aFY',
    artworkUrl: 'https://img.youtube.com/vi/f8d3bW42aFY/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'f8d3bW42aFY',
  },
  {
    id: 'yt_iu_0kOfMGD0',
    title: 'Paradisus-Paradoxum',
    artist: 'MYTH & ROID',
    album: 'Re:ZERO Season 1 OP2',
    previewUrl: 'https://www.youtube.com/watch?v=iu_0kOfMGD0',
    artworkUrl: 'https://img.youtube.com/vi/iu_0kOfMGD0/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'iu_0kOfMGD0',
  },
  {
    id: 'yt_gWCnKoEgfP0',
    title: 'Goya no Machiawase',
    artist: 'Hello Sleepwalkers',
    album: 'Noragami OP1',
    previewUrl: 'https://www.youtube.com/watch?v=gWCnKoEgfP0',
    artworkUrl: 'https://img.youtube.com/vi/gWCnKoEgfP0/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'gWCnKoEgfP0',
  },
  {
    id: 'yt_03x0bU2w9HI',
    title: 'Motteke! Sailor Fuku',
    artist: 'Aya Hirano, Emiri Kato, Kaori Fukuhara, Aya Endo',
    album: 'Lucky Star OP',
    previewUrl: 'https://www.youtube.com/watch?v=03x0bU2w9HI',
    artworkUrl: 'https://img.youtube.com/vi/03x0bU2w9HI/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '03x0bU2w9HI',
  },
  {
    id: 'yt_ULjbIMvP6A0',
    title: 'Onegai Muscle',
    artist: 'Ai Fairouz & Kaito Ishikawa',
    album: 'How Heavy Are the Dumbbells You Lift? OP',
    previewUrl: 'https://www.youtube.com/watch?v=ULjbIMvP6A0',
    artworkUrl: 'https://img.youtube.com/vi/ULjbIMvP6A0/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'ULjbIMvP6A0',
  },
  {
    id: 'yt_xHlx3rx5Bew',
    title: 'Cinderella',
    artist: 'Cidergirl',
    album: 'Komi Can\'t Communicate OP1',
    previewUrl: 'https://www.youtube.com/watch?v=xHlx3rx5Bew',
    artworkUrl: 'https://img.youtube.com/vi/xHlx3rx5Bew/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'xHlx3rx5Bew',
  },
  {
    id: 'yt_swwUoExDIng',
    title: 'Red Swan',
    artist: 'YOSHIKI feat. HYDE',
    album: 'Attack on Titan Season 3 OP1',
    previewUrl: 'https://www.youtube.com/watch?v=swwUoExDIng',
    artworkUrl: 'https://img.youtube.com/vi/swwUoExDIng/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'swwUoExDIng',
  },
  {
    id: 'yt_5txHGxJRwtQ',
    title: 'Moonlight Densetsu',
    artist: 'DALI',
    album: 'Sailor Moon OP',
    previewUrl: 'https://www.youtube.com/watch?v=5txHGxJRwtQ',
    artworkUrl: 'https://img.youtube.com/vi/5txHGxJRwtQ/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '5txHGxJRwtQ',
  },
  {
    id: 'yt_vWtOP721n0s',
    title: 'Limit Break x Survivor',
    artist: 'Kiyoshi Hikawa',
    album: 'Dragon Ball Super OP2',
    previewUrl: 'https://www.youtube.com/watch?v=vWtOP721n0s',
    artworkUrl: 'https://img.youtube.com/vi/vWtOP721n0s/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'vWtOP721n0s',
  },
  {
    id: 'yt_aqRuzjIBkxY',
    title: 'MASAYUME CHASING',
    artist: 'BoA',
    album: 'Fairy Tail OP15',
    previewUrl: 'https://www.youtube.com/watch?v=aqRuzjIBkxY',
    artworkUrl: 'https://img.youtube.com/vi/aqRuzjIBkxY/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'aqRuzjIBkxY',
  },
  {
    id: 'yt_UNjHxhljAck',
    title: 'Friend Shitai',
    artist: 'Gakuen Seikatsu-bu',
    album: 'School-Live! (Gakkougurashi!) OP',
    previewUrl: 'https://www.youtube.com/watch?v=UNjHxhljAck',
    artworkUrl: 'https://img.youtube.com/vi/UNjHxhljAck/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'UNjHxhljAck',
  },
  {
    id: 'yt_qUk1ZoCGqsA',
    title: 'Hyadain no Kakakata Kataomoi - C',
    artist: 'Hyadain',
    album: 'Nichijou OP1',
    previewUrl: 'https://www.youtube.com/watch?v=qUk1ZoCGqsA',
    artworkUrl: 'https://img.youtube.com/vi/qUk1ZoCGqsA/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'qUk1ZoCGqsA',
  },
  {
    id: 'yt_04WuoQMhhxw',
    title: 'WORK',
    artist: 'millennium parade x Sheena Ringo',
    album: 'Hell\'s Paradise: Jigokuraku OP',
    previewUrl: 'https://www.youtube.com/watch?v=04WuoQMhhxw',
    artworkUrl: 'https://img.youtube.com/vi/04WuoQMhhxw/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '04WuoQMhhxw',
  },
  {
    id: 'yt_xLGtT8WuidM',
    title: 'SPARK-AGAIN',
    artist: 'Aimer',
    album: 'Fire Force Season 2 OP1',
    previewUrl: 'https://www.youtube.com/watch?v=xLGtT8WuidM',
    artworkUrl: 'https://img.youtube.com/vi/xLGtT8WuidM/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'xLGtT8WuidM',
  },
  {
    id: 'yt_dvaosZlQqrY',
    title: 'Theme from Lupin III',
    artist: 'Yuji Ohno',
    album: 'Lupin the 3rd Part 6 OP',
    previewUrl: 'https://www.youtube.com/watch?v=dvaosZlQqrY',
    artworkUrl: 'https://img.youtube.com/vi/dvaosZlQqrY/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'dvaosZlQqrY',
  },
  {
    id: 'yt_I59V9pjEOLI',
    title: 'Kuusou Mesorogiwi',
    artist: 'Yousei Teikoku',
    album: 'Future Diary (Mirai Nikki) OP1',
    previewUrl: 'https://www.youtube.com/watch?v=I59V9pjEOLI',
    artworkUrl: 'https://img.youtube.com/vi/I59V9pjEOLI/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'I59V9pjEOLI',
  },
  {
    id: 'yt_Eq6EYcpWB_c',
    title: 'Battlecry',
    artist: 'Nujabes feat. Shing02',
    album: 'Samurai Champloo OP',
    previewUrl: 'https://www.youtube.com/watch?v=Eq6EYcpWB_c',
    artworkUrl: 'https://img.youtube.com/vi/Eq6EYcpWB_c/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'Eq6EYcpWB_c',
  },
  {
    id: 'yt_0_36iNzrEn0',
    title: 'Dead END',
    artist: 'Faylan',
    album: 'Future Diary (Mirai Nikki) OP2',
    previewUrl: 'https://www.youtube.com/watch?v=0_36iNzrEn0',
    artworkUrl: 'https://img.youtube.com/vi/0_36iNzrEn0/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '0_36iNzrEn0',
  },
  {
    id: 'yt_gz--GkzpAf8',
    title: 'Kura Kura',
    artist: 'Ado',
    album: 'SPY x FAMILY Season 2 OP',
    previewUrl: 'https://www.youtube.com/watch?v=gz--GkzpAf8',
    artworkUrl: 'https://img.youtube.com/vi/gz--GkzpAf8/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'gz--GkzpAf8',
  },
  {
    id: 'yt_Y3Xmzu0OtS8',
    title: 'Pre-Parade',
    artist: 'Rie Kugimiya, Eri Kitamura, Yui Horie',
    album: 'Toradora! OP1',
    previewUrl: 'https://www.youtube.com/watch?v=Y3Xmzu0OtS8',
    artworkUrl: 'https://img.youtube.com/vi/Y3Xmzu0OtS8/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'Y3Xmzu0OtS8',
  },
  {
    id: 'yt_X_fkh5VeOvI',
    title: 'JUSTadICE',
    artist: 'Seiko Oomori',
    album: 'Black Clover OP7',
    previewUrl: 'https://www.youtube.com/watch?v=X_fkh5VeOvI',
    artworkUrl: 'https://img.youtube.com/vi/X_fkh5VeOvI/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'X_fkh5VeOvI',
  },
  {
    id: 'yt_7aNg8cV65Os',
    title: 'FLY HIGH!!',
    artist: 'BURNOUT SYNDROMES',
    album: 'Haikyu!! Season 2 OP2',
    previewUrl: 'https://www.youtube.com/watch?v=7aNg8cV65Os',
    artworkUrl: 'https://img.youtube.com/vi/7aNg8cV65Os/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '7aNg8cV65Os',
  },
  {
    id: 'yt_cK9Z9Zcuso0',
    title: 'Guess Who Is Back',
    artist: 'Kumi Koda',
    album: 'Black Clover OP4',
    previewUrl: 'https://www.youtube.com/watch?v=cK9Z9Zcuso0',
    artworkUrl: 'https://img.youtube.com/vi/cK9Z9Zcuso0/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'cK9Z9Zcuso0',
  },
  {
    id: 'yt_XqD0oCHLIF8',
    title: 'LEveL',
    artist: 'SawanoHiroyuki[nZk]:TOMORROW X TOGETHER',
    album: 'Solo Leveling OP',
    previewUrl: 'https://www.youtube.com/watch?v=XqD0oCHLIF8',
    artworkUrl: 'https://img.youtube.com/vi/XqD0oCHLIF8/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'XqD0oCHLIF8',
  },
  {
    id: 'yt_x-AHnwQPf9s',
    title: 'EASY LOVE',
    artist: 'Sumire Uesaka',
    album: 'Don\'t Toy with Me, Miss Nagatoro OP1',
    previewUrl: 'https://www.youtube.com/watch?v=x-AHnwQPf9s',
    artworkUrl: 'https://img.youtube.com/vi/x-AHnwQPf9s/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'x-AHnwQPf9s',
  },
  {
    id: 'yt_FKIT6G_lw7c',
    title: 'Gotoubun no Kimochi',
    artist: 'Nakano-ke no Itsutsugo',
    album: 'The Quintessential Quintuplets OP1',
    previewUrl: 'https://www.youtube.com/watch?v=FKIT6G_lw7c',
    artworkUrl: 'https://img.youtube.com/vi/FKIT6G_lw7c/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'FKIT6G_lw7c',
  },
  {
    id: 'yt_HutPrLMPWw0',
    title: 'FAITH',
    artist: 'MADKID',
    album: 'The Rising of the Shield Hero OP2',
    previewUrl: 'https://www.youtube.com/watch?v=HutPrLMPWw0',
    artworkUrl: 'https://img.youtube.com/vi/HutPrLMPWw0/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'HutPrLMPWw0',
  },
  {
    id: 'yt_fpG3BPNQepY',
    title: 'Fantastic Dreamer',
    artist: 'Machico',
    album: 'KonoSuba OP1',
    previewUrl: 'https://www.youtube.com/watch?v=fpG3BPNQepY',
    artworkUrl: 'https://img.youtube.com/vi/fpG3BPNQepY/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'fpG3BPNQepY',
  },
  {
    id: 'yt_M22jx3PNxr0',
    title: 'ENAMEL',
    artist: 'SID',
    album: 'Black Butler: Book of Circus OP',
    previewUrl: 'https://www.youtube.com/watch?v=M22jx3PNxr0',
    artworkUrl: 'https://img.youtube.com/vi/M22jx3PNxr0/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'M22jx3PNxr0',
  },
  {
    id: 'yt_0i0z98M2y5U',
    title: 'Rightfully',
    artist: 'Mili',
    album: 'GOBLIN SLAYER OP1',
    previewUrl: 'https://www.youtube.com/watch?v=0i0z98M2y5U',
    artworkUrl: 'https://img.youtube.com/vi/0i0z98M2y5U/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '0i0z98M2y5U',
  },
  {
    id: 'yt_apII5VFTce0',
    title: 'TOP -English ver.-',
    artist: 'Stray Kids',
    album: 'Tower of God OP1',
    previewUrl: 'https://www.youtube.com/watch?v=apII5VFTce0',
    artworkUrl: 'https://img.youtube.com/vi/apII5VFTce0/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'apII5VFTce0',
  },
  {
    id: 'yt_oRAF2-Exzx4',
    title: 'Hikari Are',
    artist: 'BURNOUT SYNDROMES',
    album: 'Haikyu!! Season 3 OP',
    previewUrl: 'https://www.youtube.com/watch?v=oRAF2-Exzx4',
    artworkUrl: 'https://img.youtube.com/vi/oRAF2-Exzx4/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'oRAF2-Exzx4',
  },
  {
    id: 'yt_dWZAH5w8jkQ',
    title: 'Hadaka no Yuusha (Naked Hero)',
    artist: 'Vaundy',
    album: 'Ranking of Kings OP2',
    previewUrl: 'https://www.youtube.com/watch?v=dWZAH5w8jkQ',
    artworkUrl: 'https://img.youtube.com/vi/dWZAH5w8jkQ/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'dWZAH5w8jkQ',
  },
  {
    id: 'yt_2p8ig-TrYPY',
    title: 'Sing My Pleasure',
    artist: 'Vivy (Vo. Kairi Yagi)',
    album: 'Vivy: Fluorite Eye\'s Song OP',
    previewUrl: 'https://www.youtube.com/watch?v=2p8ig-TrYPY',
    artworkUrl: 'https://img.youtube.com/vi/2p8ig-TrYPY/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '2p8ig-TrYPY',
  },
  {
    id: 'yt_34wlhlQpidc',
    title: 'Rakuen',
    artist: 'Fujifabric',
    album: 'Dr. STONE Season 2 OP',
    previewUrl: 'https://www.youtube.com/watch?v=34wlhlQpidc',
    artworkUrl: 'https://img.youtube.com/vi/34wlhlQpidc/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '34wlhlQpidc',
  },
  {
    id: 'yt_2lx0S9LrOPc',
    title: 'Kyouki Chinden',
    artist: 'Yousei Teikoku',
    album: 'Future Diary (Mirai Nikki) OP3',
    previewUrl: 'https://www.youtube.com/watch?v=2lx0S9LrOPc',
    artworkUrl: 'https://img.youtube.com/vi/2lx0S9LrOPc/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '2lx0S9LrOPc',
  },
  {
    id: 'yt_C9MuI4gfyiA',
    title: 'Kyoumen no Nami',
    artist: 'YURiKA',
    album: 'Land of the Lustrous (Houseki no Kuni) OP',
    previewUrl: 'https://www.youtube.com/watch?v=C9MuI4gfyiA',
    artworkUrl: 'https://img.youtube.com/vi/C9MuI4gfyiA/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'C9MuI4gfyiA',
  },
  {
    id: 'yt_o7sZWSVH37g',
    title: 'Jungle P',
    artist: '5050',
    album: 'One Piece OP9',
    previewUrl: 'https://www.youtube.com/watch?v=o7sZWSVH37g',
    artworkUrl: 'https://img.youtube.com/vi/o7sZWSVH37g/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'o7sZWSVH37g',
  },
  {
    id: 'yt_4J8jcI0WtzM',
    title: 'Hello, World!',
    artist: 'BUMP OF CHICKEN',
    album: 'Blood Blockade Battlefront OP',
    previewUrl: 'https://www.youtube.com/watch?v=4J8jcI0WtzM',
    artworkUrl: 'https://img.youtube.com/vi/4J8jcI0WtzM/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '4J8jcI0WtzM',
  },
  {
    id: 'yt_stzAsF51T_w',
    title: '01',
    artist: 'Queen Bee (Ziyoou-vachi)',
    album: 'Undead Unluck OP1',
    previewUrl: 'https://www.youtube.com/watch?v=stzAsF51T_w',
    artworkUrl: 'https://img.youtube.com/vi/stzAsF51T_w/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'stzAsF51T_w',
  },
  {
    id: 'yt_FJqGirLjQn4',
    title: 'Makafushigi Adventure!',
    artist: 'Hiroki Takahashi',
    album: 'Dragon Ball OP',
    previewUrl: 'https://www.youtube.com/watch?v=FJqGirLjQn4',
    artworkUrl: 'https://img.youtube.com/vi/FJqGirLjQn4/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'FJqGirLjQn4',
  },
  {
    id: 'yt_oNJ4aBoRipg',
    title: 'JUST COMMUNICATION',
    artist: 'TWO-MIX',
    album: 'Mobile Suit Gundam Wing OP1',
    previewUrl: 'https://www.youtube.com/watch?v=oNJ4aBoRipg',
    artworkUrl: 'https://img.youtube.com/vi/oNJ4aBoRipg/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'oNJ4aBoRipg',
  },
  {
    id: 'yt_e-7uuV7B7mo',
    title: 'Ashita wo Narase',
    artist: 'Kavka Shishido',
    album: 'Fairy Tail OP22',
    previewUrl: 'https://www.youtube.com/watch?v=e-7uuV7B7mo',
    artworkUrl: 'https://img.youtube.com/vi/e-7uuV7B7mo/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'e-7uuV7B7mo',
  },
  {
    id: 'yt_KuZbmLLv1vM',
    title: 'Here',
    artist: 'JUNNA',
    album: 'The Ancient Magus\' Bride OP1',
    previewUrl: 'https://www.youtube.com/watch?v=KuZbmLLv1vM',
    artworkUrl: 'https://img.youtube.com/vi/KuZbmLLv1vM/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'KuZbmLLv1vM',
  },
  {
    id: 'yt_hA5P15f8i9I',
    title: 'Power of the dream',
    artist: 'lol',
    album: 'Fairy Tail Final Season OP1',
    previewUrl: 'https://www.youtube.com/watch?v=hA5P15f8i9I',
    artworkUrl: 'https://img.youtube.com/vi/hA5P15f8i9I/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'hA5P15f8i9I',
  },
  {
    id: 'yt_5zSx8QD-fkA',
    title: 'PAiNT it BLACK',
    artist: 'BiSH',
    album: 'Black Clover OP2',
    previewUrl: 'https://www.youtube.com/watch?v=5zSx8QD-fkA',
    artworkUrl: 'https://img.youtube.com/vi/5zSx8QD-fkA/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '5zSx8QD-fkA',
  },
  {
    id: 'yt_-anabfAg06U',
    title: 'Yume no Shima Shinen Kouen',
    artist: 'Susumu Hirasawa',
    album: 'Paranoia Agent OP',
    previewUrl: 'https://www.youtube.com/watch?v=-anabfAg06U',
    artworkUrl: 'https://img.youtube.com/vi/-anabfAg06U/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '-anabfAg06U',
  },
  {
    id: 'yt_8UbS2pKIyOQ',
    title: 'Netsujou no Spectrum',
    artist: 'Ikimono Gakari',
    album: 'The Seven Deadly Sins OP1',
    previewUrl: 'https://www.youtube.com/watch?v=8UbS2pKIyOQ',
    artworkUrl: 'https://img.youtube.com/vi/8UbS2pKIyOQ/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '8UbS2pKIyOQ',
  },
  {
    id: 'yt_Ui-KKFZKIq4',
    title: 'Kaimin! Anmin! Syalist Seikatsu',
    artist: 'Princess Syalis (Inori Minase)',
    album: 'Sleepy Princess in the Demon Castle OP',
    previewUrl: 'https://www.youtube.com/watch?v=Ui-KKFZKIq4',
    artworkUrl: 'https://img.youtube.com/vi/Ui-KKFZKIq4/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'Ui-KKFZKIq4',
  },
  {
    id: 'yt_1xJbdY9B3A8',
    title: 'Fatima',
    artist: 'Kanako Itou',
    album: 'Steins;Gate 0 OP',
    previewUrl: 'https://www.youtube.com/watch?v=1xJbdY9B3A8',
    artworkUrl: 'https://img.youtube.com/vi/1xJbdY9B3A8/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '1xJbdY9B3A8',
  },
  {
    id: 'yt_da3bYroZNSE',
    title: 'No.7',
    artist: 'Jibaku Shounen Band',
    album: 'Toilet-bound Hanako-kun OP',
    previewUrl: 'https://www.youtube.com/watch?v=da3bYroZNSE',
    artworkUrl: 'https://img.youtube.com/vi/da3bYroZNSE/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'da3bYroZNSE',
  },
  {
    id: 'yt_TmrosfxGifQ',
    title: 'POP TEAM EPIC',
    artist: 'Sumire Uesaka',
    album: 'Pop Team Epic OP1',
    previewUrl: 'https://www.youtube.com/watch?v=TmrosfxGifQ',
    artworkUrl: 'https://img.youtube.com/vi/TmrosfxGifQ/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'TmrosfxGifQ',
  },
  {
    id: 'yt_1caZJtPXSME',
    title: 'Futatsu no Kodou to Akai Tsumi',
    artist: 'ON/OFF',
    album: 'Vampire Knight OP1',
    previewUrl: 'https://www.youtube.com/watch?v=1caZJtPXSME',
    artworkUrl: 'https://img.youtube.com/vi/1caZJtPXSME/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '1caZJtPXSME',
  },
  {
    id: 'yt_6N5PM0iqSDA',
    title: 'WE CAN!',
    artist: 'Kishidan x Hiroshi Kitadani',
    album: 'One Piece OP19',
    previewUrl: 'https://www.youtube.com/watch?v=6N5PM0iqSDA',
    artworkUrl: 'https://img.youtube.com/vi/6N5PM0iqSDA/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '6N5PM0iqSDA',
  },
  {
    id: 'yt_qM8wxM_mcRw',
    title: 'Munou',
    artist: 'österreich',
    album: 'Tokyo Ghoul √A OP2',
    previewUrl: 'https://www.youtube.com/watch?v=qM8wxM_mcRw',
    artworkUrl: 'https://img.youtube.com/vi/qM8wxM_mcRw/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'qM8wxM_mcRw',
  },
  {
    id: 'yt_PbTDo1bWgms',
    title: 'Akatsuki no Hana',
    artist: 'Cyntia',
    album: 'Yona of the Dawn OP2',
    previewUrl: 'https://www.youtube.com/watch?v=PbTDo1bWgms',
    artworkUrl: 'https://img.youtube.com/vi/PbTDo1bWgms/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'PbTDo1bWgms',
  },
  {
    id: 'yt_SzOWbrTG_kE',
    title: 'Knock Out',
    artist: 'Taiiku Okazaki',
    album: 'MASHLE OP1',
    previewUrl: 'https://www.youtube.com/watch?v=SzOWbrTG_kE',
    artworkUrl: 'https://img.youtube.com/vi/SzOWbrTG_kE/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'SzOWbrTG_kE',
  },
  {
    id: 'yt_Bu533OKYHyc',
    title: 'Pegasus Fantasy',
    artist: 'MAKE-UP',
    album: 'Saint Seiya OP1',
    previewUrl: 'https://www.youtube.com/watch?v=Bu533OKYHyc',
    artworkUrl: 'https://img.youtube.com/vi/Bu533OKYHyc/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'Bu533OKYHyc',
  },
  {
    id: 'yt_cXabZ_-QPb0',
    title: 'Gospel of the Throttle',
    artist: 'Minutes Til Midnight',
    album: 'Drifters OP',
    previewUrl: 'https://www.youtube.com/watch?v=cXabZ_-QPb0',
    artworkUrl: 'https://img.youtube.com/vi/cXabZ_-QPb0/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'cXabZ_-QPb0',
  },
  {
    id: 'yt_Avr-Iu5vWsM',
    title: 'Never Say Never',
    artist: 'TKC',
    album: 'Danganronpa: The Animation OP',
    previewUrl: 'https://www.youtube.com/watch?v=Avr-Iu5vWsM',
    artworkUrl: 'https://img.youtube.com/vi/Avr-Iu5vWsM/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'Avr-Iu5vWsM',
  },
  {
    id: 'yt_L2uLbiIN7uo',
    title: 'Chocolat a la folie',
    artist: 'Katsumi Kahitsuka',
    album: 'Sugar Sugar Rune OP',
    previewUrl: 'https://www.youtube.com/watch?v=L2uLbiIN7uo',
    artworkUrl: 'https://img.youtube.com/vi/L2uLbiIN7uo/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'L2uLbiIN7uo',
  },
  {
    id: 'yt_OrgpX-_bFqM',
    title: 'Connect',
    artist: 'ClariS',
    album: 'Puella Magi Madoka Magica OP',
    previewUrl: 'https://www.youtube.com/watch?v=OrgpX-_bFqM',
    artworkUrl: 'https://img.youtube.com/vi/OrgpX-_bFqM/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'OrgpX-_bFqM',
  },
  {
    id: 'yt_aYtVJ7gYIWw',
    title: 'Stories',
    artist: 'Snow Man',
    album: 'Black Clover OP11',
    previewUrl: 'https://www.youtube.com/watch?v=aYtVJ7gYIWw',
    artworkUrl: 'https://img.youtube.com/vi/aYtVJ7gYIWw/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'aYtVJ7gYIWw',
  },
  {
    id: 'yt_XS-N8KfZ5EU',
    title: 'Imagination',
    artist: 'SPYAIR',
    album: 'Haikyu!! OP1',
    previewUrl: 'https://www.youtube.com/watch?v=XS-N8KfZ5EU',
    artworkUrl: 'https://img.youtube.com/vi/XS-N8KfZ5EU/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'XS-N8KfZ5EU',
  },
  {
    id: 'yt_05G4RyT9DjY',
    title: 'Kizuna no Kiseki',
    artist: 'MAN WITH A MISSION x milet',
    album: 'Demon Slayer Season 3 OP',
    previewUrl: 'https://www.youtube.com/watch?v=05G4RyT9DjY',
    artworkUrl: 'https://img.youtube.com/vi/05G4RyT9DjY/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '05G4RyT9DjY',
  },
  {
    id: 'yt_P4Z2EcYGYUI',
    title: 'Lonely Go!',
    artist: 'Brian the Sun',
    album: 'Boruto: Naruto Next Generations OP4',
    previewUrl: 'https://www.youtube.com/watch?v=P4Z2EcYGYUI',
    artworkUrl: 'https://img.youtube.com/vi/P4Z2EcYGYUI/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'P4Z2EcYGYUI',
  },
  {
    id: 'yt_5r0jdlfqeE4',
    title: 'Steppin\' out',
    artist: 'FLOW',
    album: 'Durarara!!x2 Ketsu OP',
    previewUrl: 'https://www.youtube.com/watch?v=5r0jdlfqeE4',
    artworkUrl: 'https://img.youtube.com/vi/5r0jdlfqeE4/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '5r0jdlfqeE4',
  },
  {
    id: 'yt_29pmd1QiK-4',
    title: 'Ambivalent',
    artist: 'Uru',
    album: 'The Apothecary Diaries OP2',
    previewUrl: 'https://www.youtube.com/watch?v=29pmd1QiK-4',
    artworkUrl: 'https://img.youtube.com/vi/29pmd1QiK-4/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '29pmd1QiK-4',
  },
  {
    id: 'yt_aNgT6MxOURQ',
    title: 'X.U.',
    artist: 'SawanoHiroyuki[nZk]:Gemie',
    album: 'Seraph of the End OP1',
    previewUrl: 'https://www.youtube.com/watch?v=aNgT6MxOURQ',
    artworkUrl: 'https://img.youtube.com/vi/aNgT6MxOURQ/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'aNgT6MxOURQ',
  },
  {
    id: 'yt_kupW7eDG48s',
    title: 'Kyoumu Densen',
    artist: 'ALI PROJECT',
    album: 'Another OP',
    previewUrl: 'https://www.youtube.com/watch?v=kupW7eDG48s',
    artworkUrl: 'https://img.youtube.com/vi/kupW7eDG48s/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'kupW7eDG48s',
  },
  {
    id: 'yt_6GW0wXMt2CQ',
    title: 'Date A Live',
    artist: 'sweet ARMS',
    album: 'Date A Live OP1',
    previewUrl: 'https://www.youtube.com/watch?v=6GW0wXMt2CQ',
    artworkUrl: 'https://img.youtube.com/vi/6GW0wXMt2CQ/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '6GW0wXMt2CQ',
  },
  {
    id: 'yt_osKkMKolWQ8',
    title: 'WORLD END',
    artist: 'FLOW',
    album: 'Code Geass R2 OP2',
    previewUrl: 'https://www.youtube.com/watch?v=osKkMKolWQ8',
    artworkUrl: 'https://img.youtube.com/vi/osKkMKolWQ8/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'osKkMKolWQ8',
  },
  {
    id: 'yt_Pb0N855lp_4',
    title: 'HIGHSCHOOL OF THE DEAD',
    artist: 'Kishida Kyoudan & THE Akeboshi Rockets',
    album: 'High School of the Dead OP',
    previewUrl: 'https://www.youtube.com/watch?v=Pb0N855lp_4',
    artworkUrl: 'https://img.youtube.com/vi/Pb0N855lp_4/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'Pb0N855lp_4',
  },
  {
    id: 'yt_O38EXLKLPqE',
    title: 'Kizuato',
    artist: 'Centimillimental',
    album: 'Given OP',
    previewUrl: 'https://www.youtube.com/watch?v=O38EXLKLPqE',
    artworkUrl: 'https://img.youtube.com/vi/O38EXLKLPqE/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'O38EXLKLPqE',
  },
  {
    id: 'yt_vm6R8MgqR9A',
    title: 'Rising Rainbow',
    artist: 'Misokkasu',
    album: 'Food Wars! Shokugeki no Soma OP2',
    previewUrl: 'https://www.youtube.com/watch?v=vm6R8MgqR9A',
    artworkUrl: 'https://img.youtube.com/vi/vm6R8MgqR9A/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'vm6R8MgqR9A',
  },
  {
    id: 'yt_Qy7Q77ZD_ME',
    title: 'disillusion',
    artist: 'Mami Kawada',
    album: 'Fate/stay night OP1',
    previewUrl: 'https://www.youtube.com/watch?v=Qy7Q77ZD_ME',
    artworkUrl: 'https://img.youtube.com/vi/Qy7Q77ZD_ME/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'Qy7Q77ZD_ME',
  },
  {
    id: 'yt_2oQSUoGhEBg',
    title: 'Gotobun no Katachi',
    artist: 'The Quintessential Quintuplets Cast',
    album: 'The Quintessential Quintuplets 2 OP',
    previewUrl: 'https://www.youtube.com/watch?v=2oQSUoGhEBg',
    artworkUrl: 'https://img.youtube.com/vi/2oQSUoGhEBg/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '2oQSUoGhEBg',
  },
  {
    id: 'yt_zxLtVpAAm4w',
    title: 'Golden Time',
    artist: 'Fujifabric',
    album: 'Boruto: Naruto Next Generations OP5',
    previewUrl: 'https://www.youtube.com/watch?v=zxLtVpAAm4w',
    artworkUrl: 'https://img.youtube.com/vi/zxLtVpAAm4w/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'zxLtVpAAm4w',
  },
  {
    id: 'yt_lEOrYZhMsvw',
    title: 'MAGICAL DESTROYER',
    artist: 'Aimi',
    album: 'Magical Destroyers OP',
    previewUrl: 'https://www.youtube.com/watch?v=lEOrYZhMsvw',
    artworkUrl: 'https://img.youtube.com/vi/lEOrYZhMsvw/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'lEOrYZhMsvw',
  },
  {
    id: 'yt__qaIika-QDU',
    title: 'Rakugaki Page',
    artist: 'Kankaku Piero',
    album: 'Black Clover OP6',
    previewUrl: 'https://www.youtube.com/watch?v=_qaIika-QDU',
    artworkUrl: 'https://img.youtube.com/vi/_qaIika-QDU/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '_qaIika-QDU',
  },
  {
    id: 'yt__1JvxrSlDRc',
    title: 'Pegasus Fantasy ver. Omega',
    artist: 'MAKE-UP feat. Shoko Nakagawa',
    album: 'Saint Seiya Omega OP1',
    previewUrl: 'https://www.youtube.com/watch?v=_1JvxrSlDRc',
    artworkUrl: 'https://img.youtube.com/vi/_1JvxrSlDRc/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: '_1JvxrSlDRc',
  },
  {
    id: 'yt_dWfxcRj39tg',
    title: 'Red Fraction',
    artist: 'MELL',
    album: 'Black Lagoon OP',
    previewUrl: 'https://www.youtube.com/watch?v=dWfxcRj39tg',
    artworkUrl: 'https://img.youtube.com/vi/dWfxcRj39tg/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'dWfxcRj39tg',
  },
  {
    id: 'yt_YBhsDtFUgdM',
    title: 'Kaidoku Funou',
    artist: 'Jinn',
    album: 'Code Geass OP2',
    previewUrl: 'https://www.youtube.com/watch?v=YBhsDtFUgdM',
    artworkUrl: 'https://img.youtube.com/vi/YBhsDtFUgdM/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'YBhsDtFUgdM',
  },
  {
    id: 'yt_tYuPxILnixw',
    title: 'White Noise',
    artist: 'Official HIGE DANdism',
    album: 'Tokyo Revengers Tenjiku Arc OP',
    previewUrl: 'https://www.youtube.com/watch?v=tYuPxILnixw',
    artworkUrl: 'https://img.youtube.com/vi/tYuPxILnixw/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'tYuPxILnixw',
  },
  {
    id: 'yt_Mb6TiHLMPEo',
    title: 'sky & blue',
    artist: 'GIRLFRIEND',
    album: 'Black Clover OP8',
    previewUrl: 'https://www.youtube.com/watch?v=Mb6TiHLMPEo',
    artworkUrl: 'https://img.youtube.com/vi/Mb6TiHLMPEo/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'Mb6TiHLMPEo',
  },
  {
    id: 'yt_vEklaDCExSQ',
    title: 'Gamushara',
    artist: 'Miyuna',
    album: 'Black Clover OP5',
    previewUrl: 'https://www.youtube.com/watch?v=vEklaDCExSQ',
    artworkUrl: 'https://img.youtube.com/vi/vEklaDCExSQ/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'vEklaDCExSQ',
  },
  {
    id: 'yt_cBhaKIqvUrQ',
    title: 'Dai Dai Dai Daisuki na Kimi e',
    artist: '100 Girlfriends Cast',
    album: 'The 100 Girlfriends OP',
    previewUrl: 'https://www.youtube.com/watch?v=cBhaKIqvUrQ',
    artworkUrl: 'https://img.youtube.com/vi/cBhaKIqvUrQ/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'cBhaKIqvUrQ',
  },
  {
    id: 'yt_NRI_8PUXx2A',
    title: 'Tank!',
    artist: 'Seatbelts',
    album: 'Cowboy Bebop OP',
    previewUrl: 'https://www.youtube.com/watch?v=NRI_8PUXx2A',
    artworkUrl: 'https://img.youtube.com/vi/NRI_8PUXx2A/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'NRI_8PUXx2A',
  },
  {
    id: 'yt_GasIaj6iNOU',
    title: 'Broken Games',
    artist: 'FZMZ',
    album: 'Shangri-La Frontier OP1',
    previewUrl: 'https://www.youtube.com/watch?v=GasIaj6iNOU',
    artworkUrl: 'https://img.youtube.com/vi/GasIaj6iNOU/hqdefault.jpg',
    genre: 'Anime Opening',
    category: 'anime_opening',
    source: 'youtube',
    youtubeId: 'GasIaj6iNOU',
  },

  // ==========================================
  // ANIME OST (anime_ost)
  // ==========================================
  {
    id: 'yt_a6Fl1Xl1ogg',
    title: 'ətˈæk 0N tάɪtn',
    artist: 'Hiroyuki Sawano',
    album: 'Attack on Titan Original Soundtrack',
    previewUrl: 'https://www.youtube.com/watch?v=a6Fl1Xl1ogg',
    artworkUrl: 'https://img.youtube.com/vi/a6Fl1Xl1ogg/hqdefault.jpg',
    releaseDate: '2013-06-28',
    genre: 'Anime OST',
    category: 'anime_ost',
    source: 'youtube',
    youtubeId: 'a6Fl1Xl1ogg',
  },
  {
    id: 'yt_f7SS57LFPco',
    title: 'Merry-Go-Round of Life',
    artist: 'Joe Hisaishi',
    album: "Howl's Moving Castle Soundtrack",
    previewUrl: 'https://www.youtube.com/watch?v=f7SS57LFPco',
    artworkUrl: 'https://img.youtube.com/vi/f7SS57LFPco/hqdefault.jpg',
    releaseDate: '2004-11-19',
    genre: 'Anime OST',
    category: 'anime_ost',
    source: 'youtube',
    youtubeId: 'f7SS57LFPco',
  },
  {
    id: 'yt_UFFa0QoHWvE',
    title: 'Tank!',
    artist: 'SEATBELTS',
    album: 'Cowboy Bebop Original Soundtrack',
    previewUrl: 'https://www.youtube.com/watch?v=UFFa0QoHWvE',
    artworkUrl: 'https://img.youtube.com/vi/UFFa0QoHWvE/hqdefault.jpg',
    releaseDate: '1998-05-21',
    genre: 'Anime OST',
    category: 'anime_ost',
    source: 'youtube',
    youtubeId: 'UFFa0QoHWvE',
  },
  {
    id: 'yt_QwACoXnNcwg',
    title: 'You Say Run',
    artist: 'Yuki Hayashi',
    album: 'My Hero Academia Original Soundtrack',
    previewUrl: 'https://www.youtube.com/watch?v=QwACoXnNcwg',
    artworkUrl: 'https://img.youtube.com/vi/QwACoXnNcwg/hqdefault.jpg',
    releaseDate: '2016-07-13',
    genre: 'Anime OST',
    category: 'anime_ost',
    source: 'youtube',
    youtubeId: 'QwACoXnNcwg',
  },
  {
    id: 'yt_a2GujJZfXpg',
    title: 'Sparkle',
    artist: 'RADWIMPS',
    album: 'Your Name. (Kimi no Na wa.) Soundtrack',
    previewUrl: 'https://www.youtube.com/watch?v=a2GujJZfXpg',
    artworkUrl: 'https://img.youtube.com/vi/a2GujJZfXpg/hqdefault.jpg',
    releaseDate: '2016-08-24',
    genre: 'Anime OST',
    category: 'anime_ost',
    source: 'youtube',
    youtubeId: 'a2GujJZfXpg',
  },
  {
    id: 'yt_9xya0oO5WgA',
    title: 'Number One',
    artist: 'Shiro Sagisu',
    album: 'Bleach Original Soundtrack',
    previewUrl: 'https://www.youtube.com/watch?v=9xya0oO5WgA',
    artworkUrl: 'https://img.youtube.com/vi/9xya0oO5WgA/hqdefault.jpg',
    releaseDate: '2005-05-18',
    genre: 'Anime OST',
    category: 'anime_ost',
    source: 'youtube',
    youtubeId: '9xya0oO5WgA',
  },
  {
    id: 'yt_m6kb96YWXMA',
    title: 'Fairy Tail Main Theme',
    artist: 'Yasuharu Takanashi',
    album: 'Fairy Tail Original Soundtrack Vol. 1',
    previewUrl: 'https://www.youtube.com/watch?v=m6kb96YWXMA',
    artworkUrl: 'https://img.youtube.com/vi/m6kb96YWXMA/hqdefault.jpg',
    releaseDate: '2010-01-06',
    genre: 'Anime OST',
    category: 'anime_ost',
    source: 'youtube',
    youtubeId: 'm6kb96YWXMA',
  },
  {
    id: 'yt_auLopgsgJ_s',
    title: 'Guts Theme (Gats)',
    artist: 'Susumu Hirasawa',
    album: 'Berserk Original Soundtrack',
    previewUrl: 'https://www.youtube.com/watch?v=auLopgsgJ_s',
    artworkUrl: 'https://img.youtube.com/vi/auLopgsgJ_s/hqdefault.jpg',
    releaseDate: '1997-11-06',
    genre: 'Anime OST',
    category: 'anime_ost',
    source: 'youtube',
    youtubeId: 'auLopgsgJ_s',
  },

  // ==========================================
  // VIDEOGAMES OST (videogames_ost)
  // ==========================================
  {
    id: 'yt_KK3KXAECte4',
    title: 'MEGALOVANIA',
    artist: 'Toby Fox',
    album: 'UNDERTALE Soundtrack',
    previewUrl: 'https://www.youtube.com/watch?v=KK3KXAECte4',
    artworkUrl: 'https://img.youtube.com/vi/KK3KXAECte4/hqdefault.jpg',
    releaseDate: '2015-09-15',
    genre: 'Videogames OST',
    category: 'videogames_ost',
    source: 'youtube',
    youtubeId: 'KK3KXAECte4',
  },
  {
    id: 'yt_cGufy1PAeTU',
    title: 'The Legend of Zelda Main Theme',
    artist: 'Koji Kondo',
    album: 'The Legend of Zelda Original Soundtrack',
    previewUrl: 'https://www.youtube.com/watch?v=cGufy1PAeTU',
    artworkUrl: 'https://img.youtube.com/vi/cGufy1PAeTU/hqdefault.jpg',
    releaseDate: '1986-02-21',
    genre: 'Videogames OST',
    category: 'videogames_ost',
    source: 'youtube',
    youtubeId: 'cGufy1PAeTU',
  },
  {
    id: 'yt_NTa6Xbzfq1U',
    title: 'Super Mario Bros Theme',
    artist: 'Koji Kondo',
    album: 'Super Mario Bros. Soundtrack',
    previewUrl: 'https://www.youtube.com/watch?v=NTa6Xbzfq1U',
    artworkUrl: 'https://img.youtube.com/vi/NTa6Xbzfq1U/hqdefault.jpg',
    releaseDate: '1985-09-13',
    genre: 'Videogames OST',
    category: 'videogames_ost',
    source: 'youtube',
    youtubeId: 'NTa6Xbzfq1U',
  },
  {
    id: 'yt_zkZGFNCS6iQ',
    title: 'One-Winged Angel',
    artist: 'Nobuo Uematsu',
    album: 'Final Fantasy VII Original Soundtrack',
    previewUrl: 'https://www.youtube.com/watch?v=zkZGFNCS6iQ',
    artworkUrl: 'https://img.youtube.com/vi/zkZGFNCS6iQ/hqdefault.jpg',
    releaseDate: '1997-02-10',
    genre: 'Videogames OST',
    category: 'videogames_ost',
    source: 'youtube',
    youtubeId: 'zkZGFNCS6iQ',
  },
  {
    id: 'yt_kpnW68Q8ltc',
    title: 'The Only Thing They Fear Is You',
    artist: 'Mick Gordon',
    album: 'DOOM Eternal Original Game Soundtrack',
    previewUrl: 'https://www.youtube.com/watch?v=kpnW68Q8ltc',
    artworkUrl: 'https://img.youtube.com/vi/kpnW68Q8ltc/hqdefault.jpg',
    releaseDate: '2020-04-19',
    genre: 'Videogames OST',
    category: 'videogames_ost',
    source: 'youtube',
    youtubeId: 'kpnW68Q8ltc',
  },
  {
    id: 'yt_r6PuACnHkNY',
    title: 'Hollow Knight Theme',
    artist: 'Christopher Larkin',
    album: 'Hollow Knight Original Soundtrack',
    previewUrl: 'https://www.youtube.com/watch?v=r6PuACnHkNY',
    artworkUrl: 'https://img.youtube.com/vi/r6PuACnHkNY/hqdefault.jpg',
    releaseDate: '2017-02-24',
    genre: 'Videogames OST',
    category: 'videogames_ost',
    source: 'youtube',
    youtubeId: 'r6PuACnHkNY',
  },
  {
    id: 'yt_ZNGqBDRJgvo',
    title: 'Last Surprise',
    artist: 'Shoji Meguro & Lyn',
    album: 'Persona 5 Original Soundtrack',
    previewUrl: 'https://www.youtube.com/watch?v=ZNGqBDRJgvo',
    artworkUrl: 'https://img.youtube.com/vi/ZNGqBDRJgvo/hqdefault.jpg',
    releaseDate: '2017-01-17',
    genre: 'Videogames OST',
    category: 'videogames_ost',
    source: 'youtube',
    youtubeId: 'ZNGqBDRJgvo',
  },
  {
    id: 'yt_aBkTkxKDduc',
    title: 'Sweden',
    artist: 'C418',
    album: 'Minecraft - Volume Alpha',
    previewUrl: 'https://www.youtube.com/watch?v=aBkTkxKDduc',
    artworkUrl: 'https://img.youtube.com/vi/aBkTkxKDduc/hqdefault.jpg',
    releaseDate: '2011-03-04',
    genre: 'Videogames OST',
    category: 'videogames_ost',
    source: 'youtube',
    youtubeId: 'aBkTkxKDduc',
  },
  {
    id: 'yt_0jXTBAGv9ZQ',
    title: 'Halo Theme',
    artist: 'Martin O’Donnell & Michael Salvatori',
    album: 'Halo Original Soundtrack',
    previewUrl: 'https://www.youtube.com/watch?v=0jXTBAGv9ZQ',
    artworkUrl: 'https://img.youtube.com/vi/0jXTBAGv9ZQ/hqdefault.jpg',
    releaseDate: '2002-06-11',
    genre: 'Videogames OST',
    category: 'videogames_ost',
    source: 'youtube',
    youtubeId: '0jXTBAGv9ZQ',
  },
  {
    id: 'yt_jRG0gyVFP60',
    title: 'Silver for Monsters',
    artist: 'Marcin Przybyłowicz',
    album: 'The Witcher 3: Wild Hunt Soundtrack',
    previewUrl: 'https://www.youtube.com/watch?v=jRG0gyVFP60',
    artworkUrl: 'https://img.youtube.com/vi/jRG0gyVFP60/hqdefault.jpg',
    releaseDate: '2015-05-19',
    genre: 'Videogames OST',
    category: 'videogames_ost',
    source: 'youtube',
    youtubeId: 'jRG0gyVFP60',
  },
  {
    id: 'yt_-5rAjOjTGtc',
    title: 'Aquatic Ambiance',
    artist: 'David Wise',
    album: 'Donkey Kong Country Soundtrack',
    previewUrl: 'https://www.youtube.com/watch?v=-5rAjOjTGtc',
    artworkUrl: 'https://img.youtube.com/vi/-5rAjOjTGtc/hqdefault.jpg',
    releaseDate: '1994-11-21',
    genre: 'Videogames OST',
    category: 'videogames_ost',
    source: 'youtube',
    youtubeId: '-5rAjOjTGtc',
  },
];
